name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1=py39haa95532_1
  - matplotlib-base=3.5.1=py39hd77b12b_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - plotly=5.6.0=pyhd3eb1b0_0

